[package]
name = "gl_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.15.8"
log = "0.4.17"
env_logger = "0.9.0"
glow = "0.11.2"
glutin = "0.29.1"
